### ISSUE TITLE
BK3432

### ISSUE THREAD

**Issue by AndKe** [ludwich66/Bluetooth-DMM#1]
The BT device is called BK3432
If you use a digital analyzer, or just connect FTDI (USB-UART) to the RX/TX pins, - there are only 6 or so that go to/from the DMM chip, you should easily be able to log any commands and responses the original software does to make it start transmitting data.

**Comment by ludwich66** [comment]
Hi Andre,

Thanks for helping!
Did you opend the shield? (on which meter?)

i have see darren walkers new video about the Aneng V05B.
https://www.youtube.com/watch?v=YmWRwvmwYts&t=34s <https://www.youtube.com/watch?v=YmWRwvmwYts&t=34s>

i meen to see, there is no shielding but the Video Quality is not good…

ludwich

**Comment by AndKe** [comment]
My main source of information..  also de-cased photo:
https://mysku.me/blog/aliexpress/82493.html

**Comment by ludwich66** [comment]
Great, someone was faster ;-) I couldn't find the page!

ludwich

**Comment by AndKe** [comment]
Here is a very similar project.. https://github.com/DeanCording/owonb35   - it is very likely to work with(or maybe without) some tweaking.
The protocol may even be the same..
