### ISSUE TITLE
This is not an issue just i made a windows version

### ISSUE THREAD

**Issue by webspiderteam** [ludwich66/Bluetooth-DMM#3]
Thank alot to you who made this shares and helps you. it was very helpful for me...
so i made an UWP application for aneng 9002 maybe some one need it 
Bluetooth DMM for Windows
https://github.com/webspiderteam/Bluetooth-DMM-For-Windows 
if you wish you can add this too

**Comment by kris0725pl** [comment]
With Aneng ST207 not working. Pairing error.

**Comment by ludwich66** [comment]
> With Aneng ST207 not working. Pairing error.

Please write "more"!
What did you Tested?
Wich Environment do you use?

Best Check ST207 on an Linux system with GATTool and Post your anwsers
[Bluetooth-DMM/wiki/Bluetooth---Analyses](https://github.com/ludwich66/Bluetooth-DMM/wiki/Bluetooth---Analyses)

Ludwich
