### ISSUE TITLE
Not an issue but a python version

### ISSUE THREAD

**Issue by Shiro-Nek0** [ludwich66/Bluetooth-DMM#4]
i don't have a multimeter to test it, but i made a port to python based on the 11 bits protocol from the wiki:
https://github.com/Shiro-Nek0/Bluetooth-DMM.py

**Comment by ludwich66** [comment]
Hi Shiro-Nek0,
nice that something is moving again.
I have already started the decoder with another user.
The decoder is already working (as a dummy) We had problems with BTLE. That's probably our fault though, BT is hard to understand in Python. If you can contribute something that would be great.
The day a user came with the current measuring clamp and asked.

Is this usable?
https://github.com/webspiderteam/Bluetooth-DMM-For-Windows/issues/1#issuecomment-1132004456
[Bluetooth Low Energy platform Agnostic Klient.](https://bleak.readthedocs.io/en/latest/index.html#)

**Comment by webspiderteam** [comment]
Bluetooth DMM for windows is tested working with Aneng an9002 and ZOYI ZT-300AB. I'm using it withour problem. but not all devices i think. Because st207 gives error (known by users comment). I dont have other devices and cant test them. if someone has sample datas I can decode.

**Comment by 840922704** [comment]
BLE can use bleak in python. You can see the code in my repositories: https://github.com/840922704/BLE_DMM_Client

**Comment by ludwich66** [comment]
Thanks, i added all infos
