### ISSUE TITLE
Add DIODE position for Big-DMM in Protocol Analysis page

### ISSUE THREAD

**Issue by bendtherules** [ludwich66/Bluetooth-DMM#5]
In wiki page (https://github.com/ludwich66/Bluetooth-DMM/wiki/Protocol-all-Variants), Diode: 56 is missing for Big-DMM type. Please add it.

**Comment by webspiderteam** [comment]
Thanks for informing. Somehow values looks like slipped while transfering data to wiki. it's fixed you should check again there may be more corrections.

**Comment by bendtherules** [comment]
Question: When does "Manual" text turn on? What is its bit position?
I have not been able to turn it on.

**Comment by webspiderteam** [comment]
on an9002 bit 87 is auto. if bit 87 is 1 means auto range if its 0 then means manual range
