### ISSUE TITLE
Please add my web-based implementation to wiki

### ISSUE THREAD

**Issue by bendtherules** [ludwich66/Bluetooth-DMM#6]
I made a web-based implementation to announce the readings and generate buzz tone. It only works for Big-DMM type, at the moment.
- [Github repo](https://github.com/bendtherules/multimeter-connect-web)
- [Live page](https://multimeter-speaker.netlify.app/)

**Comment by bendtherules** [comment]
Thanks for adding 👍

**Comment by ludwich66** [comment]
Thanks for Coding ;-)
