### ISSUE TITLE
ESP32 decoder

### ISSUE THREAD

**Issue by analystcmyk** [ludwich66/Bluetooth-DMM#7]
Not sure where to leave this but the ESP32 implementation of protocol decoder may be helpful for those trying to connect. 
https://m5.8266.de/?msel=stip_bt_dmm
I could not find this resource in the WIKI

**Comment by ludwich66** [comment]
The source was available at this link.
I recorded it again separately.
Thanks for the tip!
https://justanotherelectronicsblog.com/?p=930
